power.txt <- read.table("household_power_consumption_02_2007.txt", header=T, sep=";")
power.txt$Date <- as.Date(power.txt$Date, format="%d/%m/%Y")
feb_pwr <- subset(power.txt, Date >= "2007-02-01" & Date <= "2007-02-02")
active_pwr <- as.numeric(feb_pwr$Global_active_power)
feb_time <- paste(feb_pwr$Date, feb_pwr$Time)
png(filename="plot2.png", width=480, height=480, units="px")
plot(strptime(feb_time,"%Y-%m-%d %H:%M:%S"), active_pwr/500, type="n", yaxt="n", ylab="Global Active Power (kilowatts)", xlab="")
lines(strptime(feb_time,"%Y-%m-%d %H:%M:%S"), active_pwr/500)
axis(2, at=c(0,2,4,6))
dev.off()